



def full_decode(
        context_text: str,
        messages: list,
        random_seed,
        block_size=32,
        blocks_per_interval=4,
        top_p=1.0,
):
    """
    Decodes a list of covertext messages, each generated by encode_spar.
    After decoding, removes checkpoint bits and reconstructs the UTF-8 plaintext.
    """
    raise NotImplementedError("not yet implemented")
