from django.test import TestCase

from ..encoding import full_encode
from ..decoding import full_decode
from ..token_graph import build_token_graph
from ..sparsamp_utils import TOKENIZER

class SparSampTest(TestCase):

    def test_short_text(self):
        context = "Once upon a time"
        text = "attack@dawn"
        seed = 12345
        messages = full_encode(context, text, seed)
        build_token_graph(text, TOKENIZER)
        decoded_text = full_decode(context, messages, seed)
        self.assertEqual(decoded_text, text)

    def test_middle_text(self):
        context = "Once upon a time"
        text = "Star Wars is an epic space opera franchise created by George Lucas. Its story takes place a long time ago in a galaxy far, far away and centers on the conflict between good and evil—a tale of Jedi Knights and Sith Lords, droids and aliens, and the rise and fall of empires."
        seed = 12345
        messages = full_encode(context, text, seed)
        decoded_text = full_decode(context, messages, seed)
        self.assertEqual(text, decoded_text)

    def test_multiple_texts(self):
        context= "Steganography is the practice of hiding messages within other non-secret text or data."
        texts = [
            "Firefox is a free open-source web browser developed by Mozilla Foundation. Released in 2004 it challenged Internet Explorer monopoly and continues to promote web standards and user privacy. Firefox offers robust security features including Enhanced Tracking Protection which blocks third-party cookies and trackers by default. The browser supports extensive customization through add-ons and themes allowing users to personalize their browsing experience. Available across Windows macOS Linux Android and iOS platforms Firefox synchronizes bookmarks passwords and history between devices. Despite Chrome market dominance Firefox remains a vital alternative for users prioritizing privacy open-source values and control over their online data protection.",

            "Python is a high-level interpreted programming language known for its simple syntax and readability. Created by Guido van Rossum and first released in 1991 Python emphasizes code readability with significant indentation. It supports multiple programming paradigms including procedural object-oriented and functional programming. Python has a comprehensive standard library often described as batteries included philosophy. Popular in web development data science artificial intelligence machine learning and automation Python powers major platforms like YouTube Instagram and Netflix. Its vast ecosystem includes frameworks like Django Flask NumPy and TensorFlow. Python simplicity makes it ideal for beginners while its power satisfies experienced developers building complex applications.",

            "Linux is an open-source operating system kernel created by Linus Torvalds in 1991. Unlike proprietary systems Linux allows users complete control over their computing environment. Distributions like Ubuntu Fedora and Debian package Linux with software creating complete operating systems. Linux powers everything from smartphones running Android to supercomputers and web servers. Its stability security and efficiency make it preferred for server environments. The command line interface provides powerful system control though modern distributions offer user-friendly graphical interfaces. Linux philosophy emphasizes freedom collaboration and transparency. Developers worldwide contribute improvements making Linux evolve continuously. Enterprise adoption proves Linux reliability for mission-critical business applications.",

            "JavaScript is a versatile programming language essential for modern web development. Originally created by Brendan Eich in 1995 JavaScript has evolved from simple browser scripting to full-stack development. It enables interactive web pages through DOM manipulation event handling and asynchronous programming. Node.js extended JavaScript to server-side development creating a unified language ecosystem. Popular frameworks like React Angular and Vue.js simplify complex application development. JavaScript supports functional and object-oriented programming paradigms with modern features like arrow functions promises and async/await. Its ubiquity means JavaScript runs on billions of devices worldwide. Package managers like npm provide access to vast libraries accelerating development significantly.",

            "Git is a distributed version control system created by Linus Torvalds for Linux kernel development. It tracks changes in source code during software development enabling collaboration among programmers. Unlike centralized systems Git gives every developer a complete repository copy with full history. Branching and merging capabilities allow parallel development without conflicts. GitHub GitLab and Bitbucket provide cloud hosting for Git repositories adding collaboration features. Common commands include commit push pull merge and rebase for managing code versions. Git enables experimentation through branches while maintaining stable main codebases. Its distributed nature ensures code backup and availability. Modern software development relies heavily on Git for coordinating team efforts efficiently.",

            "Docker revolutionized software deployment through containerization technology making applications portable across environments. Containers package applications with dependencies ensuring consistent behavior regardless of hosting platform. Unlike virtual machines Docker containers share the host operating system kernel reducing overhead significantly. Docker images define container blueprints while registries like Docker Hub store and distribute them. Orchestration tools like Kubernetes manage container clusters at scale. Microservices architecture benefits greatly from Docker enabling independent service deployment and scaling. DevOps practices embrace Docker for continuous integration and deployment pipelines. Container isolation improves security by limiting application access to system resources. Docker simplifies development by eliminating environment configuration issues between development and production systems.",

            "React is a JavaScript library developed by Facebook for building user interfaces particularly single-page applications. Component-based architecture promotes reusable code and maintainable applications. Virtual DOM efficiently updates only changed elements improving performance over traditional DOM manipulation. JSX syntax combines HTML with JavaScript creating intuitive component templates. State management and props enable dynamic data flow between components. Hooks introduced functional components with state and lifecycle features previously exclusive to class components. The React ecosystem includes tools like Redux for state management and Next.js for server-side rendering. Large companies trust React for production applications proving its scalability. Community support provides extensive resources tutorials and third-party libraries accelerating development.",

            "Machine learning enables computers to learn from data without explicit programming for specific tasks. Supervised learning trains models using labeled data for classification and regression problems. Unsupervised learning discovers patterns in unlabeled data through clustering and dimensionality reduction. Deep learning uses neural networks with multiple layers mimicking human brain structure. Popular frameworks like TensorFlow PyTorch and scikit-learn simplify model development and training. Applications include image recognition natural language processing recommendation systems and autonomous vehicles. Data quality and quantity significantly impact model performance requiring careful preprocessing. Model evaluation metrics guide optimization and prevent overfitting. Cloud platforms offer scalable infrastructure for training complex models. Ethical considerations address bias fairness and transparency.",

            "Cybersecurity protects computer systems networks and data from digital attacks unauthorized access and damage. Common threats include malware phishing ransomware and social engineering targeting human vulnerabilities. Security measures encompass firewalls antivirus software encryption and multi-factor authentication strengthening defense layers. Penetration testing identifies vulnerabilities before malicious actors exploit them. Incident response plans prepare organizations for security breaches minimizing damage and recovery time. Zero-trust architecture assumes no user or device is trustworthy by default. Regular security updates patch known vulnerabilities preventing exploitation. Employee training reduces human error the weakest link in security chains. Compliance frameworks like ISO 27001 establish security standards. Cybersecurity careers offer diverse opportunities in growing high-demand field.",

            "Kubernetes orchestrates containerized applications providing automated deployment scaling and management across clusters. Originally developed by Google Kubernetes handles complex distributed systems efficiently. Pods represent smallest deployable units containing one or more containers. Services enable network communication between pods with load balancing capabilities. Deployments manage replica sets ensuring desired application states. ConfigMaps and Secrets separate configuration from application code improving security. Horizontal pod autoscaling adjusts resources based on demand optimizing costs. Helm charts package Kubernetes applications simplifying deployment processes. Monitoring tools like Prometheus track cluster health and performance metrics. Major cloud providers offer managed Kubernetes services reducing operational overhead. Container orchestration becomes essential for microservices architectures at scale.",

            "Blockchain technology creates immutable distributed ledgers recording transactions across network nodes. Cryptographic hashing ensures data integrity while consensus mechanisms validate new blocks. Bitcoin introduced blockchain for cryptocurrency but applications extend beyond digital money. Smart contracts execute automatically when predetermined conditions are met eliminating intermediaries. Decentralized applications run on blockchain networks providing transparency and censorship resistance. Public blockchains allow anyone participation while private blockchains restrict access for enterprise use. Mining or staking secures networks through computational work or token ownership. Scalability remains challenging as transaction volume increases affecting processing speed. Environmental concerns arise from energy-intensive proof-of-work consensus mechanisms. Blockchain promises transformation in finance supply chain healthcare and digital identity verification.",

            "Cloud computing delivers on-demand computing resources over the internet eliminating physical infrastructure management. Infrastructure as a Service provides virtual machines storage and networking components. Platform as a Service offers development environments without managing underlying infrastructure. Software as a Service delivers applications through web browsers requiring no installation. Major providers include Amazon Web Services Microsoft Azure and Google Cloud Platform. Scalability allows resources adjustment based on demand optimizing costs and performance. Geographic distribution ensures low latency and disaster recovery capabilities. Serverless computing executes code without managing servers further abstracting infrastructure. Security shared responsibility models divide obligations between providers and customers. Multi-cloud strategies avoid vendor lock-in while leveraging best services from different providers.",

            "Artificial intelligence simulates human intelligence in machines programmed to think and learn like humans. Natural language processing enables machines understanding and generating human language powering virtual assistants. Computer vision interprets visual information from cameras enabling facial recognition and autonomous navigation. Reinforcement learning trains agents through reward systems optimizing decision-making strategies. Expert systems capture human expertise in specific domains supporting complex problem-solving. Neural networks process information similarly to biological brains recognizing patterns in data. Edge AI processes data locally on devices reducing latency and preserving privacy. Explainable AI addresses black box concerns making decisions transparent and accountable. AI ethics considers bias privacy and societal impact of automated decisions. General artificial intelligence remains theoretical while narrow AI excels at specific tasks.",

            "DevOps combines software development and IT operations improving collaboration and productivity through automation. Continuous integration merges code changes frequently detecting conflicts early in development cycles. Continuous deployment automates release processes delivering features quickly and reliably to users. Infrastructure as code manages servers through configuration files enabling version control and consistency. Monitoring and logging provide visibility into system performance identifying issues proactively. Agile methodologies complement DevOps promoting iterative development and rapid feedback loops. Container orchestration streamlines application deployment across different environments. Configuration management tools maintain system states preventing drift and ensuring compliance. Microservices architecture aligns with DevOps enabling independent service deployment and scaling. Cultural transformation emphasizes shared responsibility breaking down traditional silos between development and operations teams.",

            "Data science extracts insights from structured and unstructured data using scientific methods and algorithms. Statistical analysis reveals patterns relationships and trends in datasets informing business decisions. Data cleaning and preprocessing consume significant time ensuring quality inputs for analysis. Visualization tools like Tableau and matplotlib communicate findings effectively to stakeholders. Big data technologies process massive datasets exceeding traditional database capabilities. Predictive modeling forecasts future outcomes based on historical patterns and trends. A/B testing validates hypotheses through controlled experiments measuring impact scientifically. Feature engineering creates relevant variables improving model performance significantly. Cross-validation techniques prevent overfitting ensuring models generalize to new data. Domain expertise combines with technical skills producing actionable insights solving real-world problems effectively.",

            "Web development encompasses creating websites and web applications for internet or intranet deployment. Frontend development focuses on user interfaces using HTML CSS and JavaScript technologies. Backend development handles server-side logic databases and application architecture. Full-stack developers possess skills spanning both frontend and backend development areas. Responsive design ensures websites function across devices from desktops to smartphones. Progressive web applications combine web and mobile app features providing native-like experiences. API development enables communication between different software components and services. Web accessibility ensures content availability for users with disabilities following WCAG guidelines. Performance optimization improves loading speeds through caching minification and lazy loading. Modern frameworks accelerate development while maintaining code quality and scalability standards consistently.",

            "Quantum computing leverages quantum mechanical phenomena processing information fundamentally differently than classical computers. Qubits exist in superposition states representing zero and one simultaneously unlike binary bits. Entanglement creates correlations between qubits enabling parallel processing of multiple possibilities. Quantum algorithms like Shor algorithm factor large numbers threatening current encryption methods. Error correction remains challenging due to quantum decoherence disrupting fragile quantum states. Companies like IBM Google and Microsoft invest heavily in quantum research and development. Applications include drug discovery optimization problems and cryptography advancement. Quantum supremacy demonstrates quantum computers solving specific problems faster than classical computers. Hybrid approaches combine quantum and classical computing leveraging respective strengths. Commercial viability requires significant technical breakthroughs in stability scalability and error rates.",

            "Agile methodology revolutionizes software development through iterative and incremental delivery approaches. Scrum framework organizes work into sprints typically lasting two to four weeks. Daily standups facilitate communication identifying blockers and synchronizing team efforts effectively. Product backlogs prioritize features based on business value and customer needs. Retrospectives encourage continuous improvement examining what worked and what needs adjustment. Cross-functional teams possess diverse skills eliminating dependencies and bottlenecks. Customer collaboration replaces contract negotiation fostering better understanding of requirements. Adaptive planning accommodates changes rather than following rigid predetermined plans. User stories describe features from end-user perspectives ensuring value delivery. Agile principles emphasize working software over comprehensive documentation though documentation remains important for maintenance.",

            "REST API design principles enable scalable web services through standardized architectural constraints. Stateless communication ensures each request contains necessary information without server-side session storage. Resource-based URLs identify entities using nouns rather than verbs maintaining clarity. HTTP methods GET POST PUT DELETE map to CRUD operations consistently. JSON format dominates data exchange providing human-readable lightweight structure. Authentication mechanisms like OAuth protect resources from unauthorized access effectively. Versioning strategies manage API evolution without breaking existing client implementations. Rate limiting prevents abuse protecting server resources from overwhelming request volumes. Documentation tools like Swagger provide interactive API exploration improving developer experience. Hypermedia links enable API discoverability though adoption remains limited in practice. RESTful design promotes interoperability between diverse systems and platforms.",

            "Network security protects data during transmission and prevents unauthorized network access attempts. Firewalls filter traffic based on predetermined rules blocking potentially harmful connections. Virtual private networks encrypt communications providing secure remote access to resources. Intrusion detection systems monitor network traffic identifying suspicious patterns and anomalies. Network segmentation isolates critical resources limiting breach impact through containment. SSL/TLS protocols encrypt web traffic protecting sensitive information from interception. Port scanning identifies open services revealing potential attack vectors requiring protection. DMZ architecture separates public-facing services from internal networks improving security. Network access control enforces policies ensuring only authorized devices connect. Zero-trust networking verifies every connection regardless of source location eliminating implicit trust assumptions completely."
        ]
        seed = 23456789
        i = 0
        for i in range(4, len(texts)):
            text = texts[i]
            print(f"⚠️ Running test {i} of {len(texts)}")
            messages = full_encode(context, text[:200], seed)
            decoded_text = full_decode(context, messages, seed)
            self.assertEqual(decoded_text, text[:200])

    def test_decoding_with_ta(self):
        context = "Once upon a time"
        text = "Star Wars is an epic space opera franchise created by George Lucas. Its story takes place a long time ago in a galaxy far, far away and centers on the conflict between good and evil—a tale of Jedi Knights and Sith Lords, droids and aliens, and the rise and fall of empires."
        seed = 12345
        messages = [" you seem to have trouble wrapping your mind around a problem. Each headache causes you to work out actionable solutions. Run, charter, read notes of 'Yhmump, run, aren't you getting frustrated?' Get out of your hurry and leapfrog until you have the energy, the motivation, the willpower, the mindful choice to fly. Soon you put a stop to any and all fear and build an inner source of discipline. Allow your body to resist wherever unlimited stress might endanger you.\n\nAnd", ", he could scarcely have minded the lack of consolation in neglecting to pay the cost of another year's rental — distances that rendered him an indispensable tinker or the porter of trips in these trials, thrown up with serious grief and ruin. But this present tail was full of satisfaction for sometimes a fortnight — in which case his partiality would have absolutely destroyed his sagacity; but even then not to scratch, an infinite while more. A great shyness struck and fed upon him on account of the hospitality of the summer", ', after nearly forty thousand years, King Alexander the Great created a city, Nevia, in the land of the sword. From this time, shortly before his Death, Alexander took refuge in Marganis in the middle of a Great War which occupied one of the years 1,000 BCE to 433 CE. With admittance, Alexander built his first roads. He then hated its geography, and gave it to Persia and changed it to Flowers, telling it that only true warriors would fight like that. (', ', the Nevada landscape presented a threat to the much coveted modern ranch each year. We see abundant biological diversity of different kinds roaming the landscape, from and to nest of deer in zippo lagoons to canines in douglas fir stumps—large, solitary mammals that can move through the gaps with no visible stripe of sunlight. Not to mention a recently discovered five-foot coal pipe found at one of the largest hog habitat areas in Nevada Parks and Country. Stripes bridging through the swamps proved', ' I would have resized too much but then I started looking closer and more and until I could see their busts, delicate breasts and posed bodies.\n\nIt is that view', ', Mary W. Snow recognized that every single strategy']
        decoded_text = full_decode(context, messages, seed)
        self.assertEqual(decoded_text, text)

    def test_long_text(self):
        context = "Once upon a time"
        text = """Star Wars is an epic space opera franchise created by George Lucas. Its story takes place a long time ago in a galaxy far, far away and centers on the conflict between good and evil—a tale of Jedi Knights and Sith Lords, droids and aliens, and the rise and fall of empires.

The saga began in 1977 with the release of Star Wars (later subtitled Episode IV: A New Hope). It quickly became a global phenomenon and laid the foundation for one of the most influential franchises in film history. The original trilogy tells the story of a farm boy named Luke Skywalker, the wise Obi-Wan Kenobi, Princess Leia, and the charming smuggler Han Solo, as they fight against the Galactic Empire ruled by the evil Emperor Palpatine and his fearsome enforcer, Darth Vader.

Beyond the original trilogy, the Star Wars story is expanded through a prequel trilogy that dives into the rise of Anakin Skywalker and his transformation into Darth Vader—focusing on the downfall of the Jedi Order and the rise of the Empire. The sequel trilogy, developed decades later, continues the story with a new generation of heroes and villains, building on classic themes of hope, redemption, destiny, and the ongoing battle between light and dark.



The universe is marked by advanced technology, such as starships that travel at lightspeed, planets of every imaginable environment, and incredible weapons like lightsabers and the planet-destroying Death Star. At the heart of the saga is the Force—an energy field created by all life that can be harnessed for good or evil, granting its users extraordinary abilities. This duality of the Force is embodied by its two great orders: the noble Jedi, who serve as peacekeepers, and the power-hungry Sith, who seek dominance over the galaxy.

The series spans centuries of galactic history—featuring epic battles, dramatic betrayals, powerful friendships, and moral dilemmas. Characters like Yoda, Chewbacca, R2-D2, C-3PO, Lando Calrissian, and many more have become cultural icons.

The impact of Star Wars extends well beyond the films. It includes animated and live-action TV series, novels, comics, video games, toys, and even theme parks, creating a vast expanded universe and a passionate fan community. Star Wars continues to inspire new generations with stories of courage, hope, and the belief that even the smallest person can change the fate of the galaxy.
"""
        seed = 12345
        messages = full_encode(context, text, seed)
        decoded_text = full_decode(context, messages, seed)
        self.assertEqual(decoded_text, text)
